array = [ '1', '2', '3' ]

rescue Exception => e
  # ...
end
